### ISSUE TITLE
 i get this  8  Positive directional derivative for linesearch when i run single point optimization 

### ISSUE THREAD

**Issue by eng-jamal2023** [mdolab/MACH-Aero#117] opened 2023-10-20 03:37 UTC
Dear ,

I am writing to bring to your attention an error that I encountered while using MACHAERO Specifically, when I attempted to run a single point optimization, I received an error message indicating that Positive directional derivative for linesearch as it attach here all the simulation output 
[mycd0.01.txt](https://github.com/mdolab/MACH-Aero/files/13049659/mycd0.01.txt)
. As a result, I am unable to proceed with my work and require your assistance in resolving this issue.

I have attempted to address the problem by adjusting the bound lower and upper values for the shape, thickness, and volume constraints. Unfortunately, this did not resolve the issue, and I continue to receive the same error message.

I would greatly appreciate any advice or guidance you can provide on how to solve this problem. I am eager to continue using your software and would like to ensure that I can do so without any further issues.

Thank you for your attention to this matter.  
here i will attach the coordinate of the airfoil 

[s809.txt](https://github.com/mdolab/MACH-Aero/files/13049679/s809.txt)

**Comment by eirikurj** [comment] 2023-10-20 11:00
@eng-jamal2023 please study the stdout carefully. The output file you attached is littered with warning and error messages (like the ones shown below), which renders the optimization results/output meaningless. Please check your geometry parameterization and setup. The failed mesh (indicated below) might help you identify what the source of the issue is. 

Closing as there are several discussions open on the same topic (https://github.com/mdolab/MACH-Aero/discussions/110, https://github.com/mdolab/MACH-Aero/discussions/111, https://github.com/mdolab/MACH-Aero/discussions/116). Please continue the discussion there.
```
#--------------------------- !!! Error !!! ----------------------------
#* returnFail called by processor 3
#* Run-time error in procedure metric
#* Error message: Negative volumes present in grid.
#*
#----------------------------------------------------------------------
#
#                      Warning
# Symmetry boundary face BC3 of zone domain.00001 is not planar.
# Maximum deviation from the mean normal:  1.80000E+02 degrees
#
#                      Warning
# 11 bad quality volumes found.
# Computation will continue, but be aware of this.
#
Fatal failure during mesh warp! Bad mesh is written in output directory as failed_mesh_fc_001.cgns
```

**Closed by eirikurj** 2023-10-20 11:00 UTC

**Comment by eng-jamal2023** [comment] 2023-10-26 06:19
dear eirikurj

Could you tell me which software or code you use to create airfoil coordinates? If the airfoil is not on the list in the database of MDOLAB, how can I create the points around it? I understand that the points around the airfoil are not equally distributed and are similar to mesh distribution points. Can you give me an idea of how I can create these points so that I can run my simulation without any errors? Thank you very much
