### ISSUE TITLE
Faulty source code of SLSQP.py - airfoil_opt.py

### ISSUE THREAD

**Issue by Hokage7940** [mdolab/MACH-Aero#137] opened 2023-12-29 05:52 UTC
## Description
The problem is related to the Airfoil optimization MACH Aero framework of MDO Lab. While running the airfoil_opt.py code, it gives an error indicating that there is an error in the SLSQP.py

### Steps to reproduce issue
Run Bash in windows. Enter the docker through bash and run the following,
1. Run genMesh.py
2. Run genFFD.py
3. Run airfoil_opt.py

### Current behavior

When I run "mpirun -np 4 python airfoil_opt.py | tee output.txt" in bash, the program runs properly till the following:

```
+-------------------------------------------------------------------------------+
|                   Sparsity structure of constraint Jacobian                   |               |
+-------------------------------------------------------------------------------+
```

Then it displays the following error:

```
ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 16 -- input 'D' not compatible to 'd'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mdolabuser/mount/mach-aero/SA7038/airfoil_opt.py", line 270, in <module>
    sol = opt(optProb, MP.sens, storeHistory=os.path.join(args.output, "opt.hst"))
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 218, in __call__
    slsqp.slsqp(m, meq, la, n, xs, blx, bux, ff, gg, df, dg, acc, maxit,
ValueError: failed in converting 5th argument `x' of slsqp.slsqp to C/Fortran array
```
### Expected behavior
it should produce results similar to the results provided in the following:
https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/machAeroTutorials/airfoilopt_singlepoint.html

Note:
You can excess the pySLSQP.py at:
https://github.com/mdolab/pyoptsparse/tree/main/pyoptsparse/pySLSQP

**Comment by nwu63** [comment] 2024-01-05 17:24
Duplicate of #96.

**Closed** 2024-01-05 17:25 UTC
